version: '3.4'

services:
  authmicroservice:
    image: authmicroservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
